name: Build and Release Packet Analyzer

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Upload package to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/packet-analyzer-1.0.0.tar.gz
        asset_name: packet-analyzer-1.0.0.tar.gz
        asset_content_type: application/gzip
